### ISSUE TITLE
Invalid npm package name

### ISSUE THREAD

**Issue by snhasani** [GoogleChrome/voice-memos#10]
Package name in package.js file is invalid and occur error when npm install.
valid npm package name role: https://docs.npmjs.com/files/package.json#name

**Comment by yoanmarchal** [comment]
switch from "Voice Memos" to "VoiceMemos" in package.json it works

**Comment by addyosmani** [comment]
I'd recommend switching to `voice-memos` or `VoiceMemos`. Confirmed the current name field is invalid.

**Comment by snhasani** [comment]
I'm sorry for this mistake, clicking the wrong button :/
`voice-memos` seems is good.

**Comment by techniq** [comment]
:+1:

**Comment by paullewis** [comment]
Fixed in e8efcadd615fa145850a966b0a06a4a7980f9a8f
