### ISSUE TITLE
How can make it work locally?

### ISSUE THREAD

**Issue by zzarcon** [GoogleChrome/voice-memos#14]
I was trying to run the project locally but I can't...

Can you add some steps to follow in order to run the project locally?

Thanks!

**Comment by rpunkfu** [comment]
Hi @zzarcon, here's the way I did it:
1. Please install this [Google App Engine SDK For Python](https://cloud.google.com/appengine/downloads#Google_App_Engine_SDK_for_Python).
2. Run SDK app to create symlinks for `dev_appserver.py`.
3. Run `npm install` in **voice-memos/**.
   
   3.1. If you're using node >= 4.0, you should propably run `npm uninstall --save-dev gulp-sass` and then `npm install --save-dev gulp-sass`.
4. Run `gulp` in **voice-memos/**.
5. Run `dev_appserver.py voice-memos/`
6. Enjoy your local version of app :).

**Comment by zzarcon** [comment]
@oskarcieslik thanks man, works like a charm now.

Would be really nice to add it to the `Readme` :dancer:

**Comment by rpunkfu** [comment]
@zzarcon Created pull request with instructions in `readme` :)
