### ISSUE TITLE
Update to use MediaRecorder instead of Web Audio

### ISSUE THREAD

**Issue by juberti** [GoogleChrome/voice-memos#17]
We just enabled MediaRecorder in Chrome 49. Would be great to see Voice Memos start using it instead of manually capturing PCM data from web audio.

@samdutton
@miguelao

**Comment by paullewis** [comment]
Yes! It's on my radar, hoping to wire it up next week :)

**Comment by paullewis** [comment]
This is in the latest deployed version :tada:
