### ISSUE TITLE
Why had you used Python in the JavaScript project?

### ISSUE THREAD

**Issue by alex-chuev** [GoogleChrome/voice-memos#22]
This creates real difficulties for running the application locally...

**Comment by paullewis** [comment]
Hi Alex, Python hosting is fairly standard with my job (App Engine), and I felt that the availability of the [Google App Engine SDK](https://cloud.google.com/appengine/downloads) would make feasible for most developers to run the app locally, since they typically have admin rights to their machine.

**Comment by amio** [comment]
While, still it's an unnecessary step for user to learn a PWA, I think a static webapp on github pages should be enough for the demo.

**Comment by GersonRosales** [comment]
I used javascript only but had problem with the views, so replaced this directives of python here https://github.com/GoogleChrome/voice-memos/blob/master/src/index.html#L30
```
{% include "dist/styles/voicememo-core.css" %}
```
for this
```
<link rel="stylesheet" type="text/css" href="/styles/voicememo-core.css">
```
then i execute `gulp dev` and ready

i am using web server for chrome - https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb
