### ISSUE TITLE
Microphone access doesn't seem to work in embedded twitter webviews

### ISSUE THREAD

**Issue by borismus** [GoogleChrome/voice-memos#4]
Either fix the issue or indicate to the user that the app won't work

**Comment by paullewis** [comment]
Adding @gauntface to this, if he has time / ideas. So far as I can tell there's no way to programmatically detect this is running in a webview. I'll keep trying though.

**Comment by paullewis** [comment]
Actually `getUserMedia` throws so I can use that. Fixed in 65f6e74a75125651abfe48dca5d0291795d8195a
