### ISSUE TITLE
Self-XSS possible in memo title/description

### ISSUE THREAD

**Issue by cvan** [GoogleChrome/voice-memos#5]
1. Create a new memo.
2. Add a title or description with crafty HTML.
3. Save the memo.
4. Notice you just XSS'd yourself.

Here's the HTML I used:

``` html
'"><marquee><img src="https://upload.wikimedia.org/wikipedia/en/e/e2/Tintin_and_Snowy.png" onload="alert('xss')"></marquee><"'
```

![screenshot 2015-05-18 00 11 41](https://cloud.githubusercontent.com/assets/203725/7675887/bcd36fde-fcf2-11e4-8028-3fdd28b481af.png)

**Comment by paullewis** [comment]
Fixed and deployed. Thanks very much for the heads up!
